services:
  - type: web
    name: virtual-lab
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_TYPE
        value: sqlite
      - key: DB_SQLITE_PATH
        value: /var/www/html/data/experiments.db
    disk:
      name: virtual-lab-disk
      mountPath: /var/www/html/data
      sizeGB: 1

